### ISSUE TITLE
the module is invalid

### ISSUE THREAD

**Issue by Hunam6** [TheBoringDude/venv#1]
`builder error: cannot import module "venv" (not found)`

It may be due to commas.
![image](https://user-images.githubusercontent.com/38606542/122949747-33005f80-d37c-11eb-9d48-ae7dd1cd9889.png)

**Comment by tbdsux** [comment]
readme usage is wrong, if you installed it using `v install`,

can you try to re-install and import it using: 
```v
import theboringdude.venv
```

**Comment by Hunam6** [comment]
Okay thanks!
